name: Start Actions on Commit for Updating Documentation
on:
  push:
      branches:
        - '**'
      # paths:
      # - 'clucker/**'
  
jobs:          
  documentation:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
         python-version: '3.10'
      
      - name: Clone Submodule clucker and repo_copilot
        run: |
          git submodule init
          git submodule update

      - name: Clone Submodule for code2flow
        run: |
          cd repo_copilot
          git submodule init
          git submodule update

      - name: Get cluker's branch name
        run: |
            cd clucker
            echo "BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_ENV
        id: branch_name

      - name: Install repo_copilot's dependencies
        run: |
          cd repo_copilot
          pip3 install -r requirements.txt

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Start ollama server
        run: curl -fsSL https://ollama.com/install.sh | sh
  
      - name: Run Llama 3
        run: ollama run llama3

      - name: Run update documentation script
        run: |
          cd repo_copilot/repo_documentation
          python update_app.py "${{ env.BRANCH_NAME }}"

      - name: Commit and push if changes in clucker
        run: |
          cd clucker
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "Documentation Updated" && git pull --rebase && git push)

      - name: Commit and push if changes in repo_copilot
        run: |
          cd repo_copilot
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "Documentation Updated" && git pull --rebase && git push)